name: CI/CD Deployment

on:
  push:
    branches:
      - main  # Run workflow on commits to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Checkout the latest code from the repo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Adjust Python version if needed

    #- name: Install Dependencies
     # run: |
      #  python -m pip install --upgrade pip
       # pip install -r requirements.txt

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /var/www/production  # Change to your project directory
          git pull origin main    # Pull latest changes
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate django_env
          systemctl restart gunicorn        # Restart Gunicorn
          systemctl reload nginx
